// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiasGarden.DataAccess.Data;

#nullable disable

namespace SiasGarden.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240502093246_assStartImgUrlToProduct")]
    partial class assStartImgUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductSubCategory", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoriesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "SubCategoriesId");

                    b.HasIndex("SubCategoriesId");

                    b.ToTable("ProductsSubCategories", (string)null);
                });

            modelBuilder.Entity("SiasGarden.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Rosor"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Perenner"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Fröer"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Rhododendron"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Buskar"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Träd"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Tillbehör"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Redskap"
                        });
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BulkDiscount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("StartImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulkDiscount = 10,
                            CategoryId = 1,
                            Description = "Sensationell storblommig ratbttros med stora, fyllda, svagt doftande gräddvita blommor med körsbärsröda kanter. Blommar från juni till oktober. Trivs i sol-halvskugga i väldränerad, näringsrik jord",
                            LatinName = "Rosa Taneiglat",
                            Name = "Nostalgi",
                            Number = 10,
                            Price = 699.0
                        },
                        new
                        {
                            Id = 2,
                            BulkDiscount = 10,
                            CategoryId = 1,
                            Description = "Otroligt vacker ros med buskigt växtsätt. Remonterar från sommar till höst med fylllda gula blommor och röda anstrykningar på yttre kronbladen. Friskt sort. Trovs soligt i väldränerad, näringsrik jord.",
                            LatinName = "Rose Lampion",
                            Name = "Lampion",
                            Number = 10,
                            Price = 999.0
                        },
                        new
                        {
                            Id = 3,
                            BulkDiscount = 15,
                            CategoryId = 2,
                            Description = "Vacker lättodlad perenn med hjärformade blommor i rött och vitt. Klipp ner efter blomning för chans till ytterligare en blomning senare på sommaren. Finast i halvskuggigt, skyddat läge.",
                            LatinName = "Lamprocapnos specabilis Valentine",
                            Name = "Löjtnatshjärta Valentine",
                            Number = 20,
                            Price = 199.0
                        },
                        new
                        {
                            Id = 4,
                            BulkDiscount = 10,
                            CategoryId = 2,
                            Description = "Vacker lättodlad perenn med hjärformade blommor i rosa och vitt. Klipp ner efter blomning för chans till ytterligare en blomning senare på sommaren. Finast i halvskuggigt, skyddat läge.",
                            LatinName = "Lamprocapnos specabilis",
                            Name = "Löjtnadshjärta",
                            Number = 10,
                            Price = 179.0
                        },
                        new
                        {
                            Id = 5,
                            BulkDiscount = 10,
                            CategoryId = 1,
                            Description = "Klasblommig ros med kompakt växtsätt. Remonterar från sommar till höst med fyllda aprikosgula blommor. Medelstark doft. Frisk sort. Trivs i sol-halvskugga i väldränerad näringsrik jord.",
                            Name = "Hansestadt Rostock",
                            Number = 20,
                            Price = 699.0
                        },
                        new
                        {
                            Id = 6,
                            BulkDiscount = 5,
                            CategoryId = 2,
                            Description = "Mattbildande låg timjan som med sitt kompakta växtsätt av små gröna blad och rik blomning i rödviolett blir perfekt marktäckare i stenparti eller som kantväxt. Trivs soligt i väldränerad, mager jord.",
                            LatinName = "Thymus Coccineus",
                            Name = "Purpurtimjan",
                            Number = 3,
                            Price = 59.899999999999999
                        },
                        new
                        {
                            Id = 7,
                            BulkDiscount = 10,
                            CategoryId = 5,
                            Description = "Buske med vackra konformade blomklasar som ändrar färg från vitt till rosa när de åldras. Trivs i sol-halvskugga i näringsrik, väldränderad och fuktighetshållande jord.",
                            LatinName = "Hudrangea panicilata Sundae fraise",
                            Name = "Vippoprtensia Sundaw fraise",
                            Number = 5,
                            Price = 699.0
                        },
                        new
                        {
                            Id = 8,
                            BulkDiscount = 10,
                            CategoryId = 5,
                            Description = "Buske med vackra konformade blomklasar som ändrar färg från vitt till rosa när de åldras. Trivs i sol-halvskugga i näringsrik, väldränderad och fuktighetshållande jord.",
                            LatinName = "Hudrangea panicilata Living Pink & Rose",
                            Name = "Vipphortensia Living Pink & Rose",
                            Number = 5,
                            Price = 349.0
                        });
                });

            modelBuilder.Entity("SiasGarden.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("SiasGarden.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Klätterros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buskros"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rabattros"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Azalea"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Parkrhododendron"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jord"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bärbuskar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fruktträd"
                        });
                });

            modelBuilder.Entity("ProductSubCategory", b =>
                {
                    b.HasOne("SiasGarden.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiasGarden.Models.SubCategory", null)
                        .WithMany()
                        .HasForeignKey("SubCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.HasOne("SiasGarden.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SiasGarden.Models.ProductImage", b =>
                {
                    b.HasOne("SiasGarden.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
