// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiasGarden.DataAccess.Data;

#nullable disable

namespace SiasGarden.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240617151656_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SiasGarden.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SiasGarden.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rosor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Perenner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Klängväxter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Buskar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Träd"
                        });
                });

            modelBuilder.Entity("SiasGarden.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SiasGarden.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Light")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Blommar rikligt med mörkt blåviolett blommor och har ett kompakt, lågväxande växtsätt. Utvecklas bäst i full sol på väldränerad jord. En av de härdigaste sorterna.",
                            Height = 60,
                            LatinName = "Lavendula augustifolia 'Hidcote'",
                            Light = "Sol",
                            Name = "Hidcote",
                            Price = 59.0,
                            SubCategoryId = 1,
                            ZoneTo = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Blomvillig och lättskött perenn för soliga lägen med djupt, mörklila blomax på purpurfärgade stjälkar. Blommar rikligt och länge.",
                            Height = 60,
                            LatinName = "Salvia nemorosa 'Caradonna'",
                            Light = "Sol",
                            Name = "Caradonna",
                            Price = 49.0,
                            SubCategoryId = 1,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vacker lättodlad perenn med hjärformade blommor i rött och vitt. Klipp ner efter blomning för chans till ytterligare en blomning senare på sommaren. Finast i halvskuggigt, skyddat läge.",
                            Height = 40,
                            LatinName = "Lamprocapnos specabilis 'Valentine'",
                            Light = "Sol till halvskugga",
                            Name = "Valentine",
                            Price = 199.0,
                            SubCategoryId = 2,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vacker, lättodlad perenn med hjärtformade blommor i vitt. Klipp ner efter blomning för chans till ytterligare en blomning senare på sommaren. Finast i halvskuggigt, skyddat läge. för chans till ytterligare en blomning senare på sommaren. Finast i halvskuggigt, skyddat läge.",
                            Height = 40,
                            LatinName = "Lamprocapnos spectabilis 'Alba'",
                            Light = "Sol till halvskugga",
                            Name = "Alba",
                            Price = 84.0,
                            SubCategoryId = 2,
                            ZoneTo = 9
                        },
                        new
                        {
                            Id = 5,
                            Description = "Klasblommig ros med kompakt växtsätt. Remonterar från sommar till höst med fyllda aprikosgula blommor. Medelstark doft. Frisk sort. Trivs i sol-halvskugga i väldränerad näringsrik jord.",
                            Height = 80,
                            Light = "Sol till halvskugga",
                            Name = "Hansestadt Rostock",
                            Price = 289.0,
                            SubCategoryId = 4,
                            ZoneTo = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sensationell storblommig rabattros med stora, fyllda, svagt doftande gräddvita blommor med körsbärsröda kanter. Blommar från juni till oktober. Trivs i sol-halvskugga i väldränerad, näringsrik jord.",
                            Height = 70,
                            Light = "Sol",
                            Name = "Nostalgi",
                            Price = 299.0,
                            SubCategoryId = 4,
                            ZoneTo = 4
                        },
                        new
                        {
                            Id = 7,
                            Description = "Buskros med upprätt och tätt växtsätt. Bladverket är läderartat, mörkgrönt och glänsande. Blommar med tätt fyllda, mörkt sammetsröda blommor som har en medelstark doft. Riklig blomning nästan oavbrutet från juni och in på senhösten. Mycket användbar då den kan planteras i grupper, tillsammans med perenner, som kantväxt och häckväxt, blir även fin i kruka. Trivs bäst i soliga lägen i näringsrik jord.",
                            Height = 150,
                            Light = "Sol",
                            Name = "Isabel Renaissance",
                            Price = 345.0,
                            SubCategoryId = 3,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Buskros med ett kraftigt, buskigt växtsätt. Bladverket är friskt, grönt där all nytillväxt är vackert röd. Praktfull blomning med klasar av gula, fyllda blommor som ljusnar under blomningen till en härlig svavelgul nyans. Doftar angenämt och tål regn bra. Är en frisk ros som är motståndskraftig mot olika svampsjukdomar",
                            Height = 100,
                            Light = "Sol",
                            Name = "High Voltage",
                            Price = 345.0,
                            SubCategoryId = 3,
                            ZoneTo = 5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vacker hybrid som blommar länge från sommar till tidig höst med sammetsröda blommor mot mörkgrönt bladverk. Trivs i sol–halvskugga i fukthållande, väldränerad jord. Beskärningsgrupp 2.",
                            Height = 200,
                            Light = "Sol-halvskugga",
                            Name = "Hisako",
                            Price = 350.0,
                            SubCategoryId = 5,
                            ZoneTo = 6
                        },
                        new
                        {
                            Id = 10,
                            Description = "Storblommig klematis med läckert körsbärsröda blommor. Blommar under en lång tid. Blomrik och tålig. För soliga till halvskuggiga lägen. Beskärningsgrupp 3.",
                            Height = 400,
                            Light = "Sol-halvskugga",
                            Name = "Ville de Lyon",
                            Price = 199.0,
                            SubCategoryId = 5,
                            ZoneTo = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lonicera heckrottii 'Goldflame' är en lättodlad och vacker kaprifol. Sorten är kraftfull och snabbväxande. Blommar med rörformiga, rosa/rödrosa blommor under juni - augusti. På hösten kommer dekorativa oätliga röda bär. Bladen är ovala, medelstora, blågröna och ger fin gul höstfärg. Doften är frisk, intensivt och fantastisk. Sorten är mycket tålig och ger riklig blomning på en solig plats. Älskas av fjärilar, bin och humlor",
                            Height = 350,
                            LatinName = "Lonicera heckrottii 'Goldflame'",
                            Light = "Sol-halvskugga",
                            Name = "Goldflame",
                            Price = 28.0,
                            SubCategoryId = 6,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Färggrann sort med kraftigt, slingrande och täckande växtsätt med frodigt blågrönt bladverk. Blommar rikligt med doftande, brandgula blommor varvat med bronsgula knoppar. Bildar röda, oätliga bär. Trivs i sol till halvskugga på väldränerad, näringsrik jord.3.",
                            Height = 450,
                            LatinName = "Lonicera x tellmanniana'",
                            Light = "Sol-halvskugga",
                            Name = "Tellmannskaprifol",
                            Price = 199.0,
                            SubCategoryId = 6,
                            ZoneTo = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Elegant, storblommig sort med buskigt, upprätt växtsätt. Blommar länge med gräddvita, fylliga klasar som skiftar till mörkrosa och avslutas i mörkrosa nyanser. Trivs i sol till halvskugga på mullrik, lätt kemiskt sur jord.",
                            Height = 250,
                            LatinName = "Hydrangea paniculata 'Vanille-Fraise'",
                            Light = "Sol-halvskugga",
                            Name = "Vanille-Fraise",
                            Price = 299.0,
                            SubCategoryId = 15,
                            ZoneTo = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Syrenbuddleja kallas även för fjärilsbuske, då den är känd för att locka till sig fjärilar. Fungerar att planteras både som solitär och i grupp. Anses vara mindre smaklig för rådjur.",
                            Height = 199,
                            LatinName = "Buddleja davidii 'Royal Red'",
                            Name = "Syrenbuddleja",
                            Price = 340.0,
                            SubCategoryId = 7,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Kraftig med lätt överhängande grenar och rik skörd av svarta bär i rejäla klasar. Härdig och motståndskraftig mot mjöldagg. Trivs i sol-halvskugga i väldränerad, näringsrik, fuktighetshållande jord.",
                            Height = 150,
                            LatinName = "Ribes nigrum 'Öjebyn'",
                            Light = "Sol-halvskugga",
                            Name = "Öjebyn",
                            Price = 149.0,
                            SubCategoryId = 13,
                            ZoneTo = 6
                        },
                        new
                        {
                            Id = 16,
                            Description = "Frodig slingerväxt som får gräddvita, doftande blommor och små äggformade, bruna frukter med hårigt skal och grönt, sötsyrligt fruktkött. Självfertil men gynnas av samplantering med hanplanta. Ger bäst skörd på en varm solig och skyddad plats, gärna i växthus.",
                            Height = 400,
                            LatinName = "Actinidia deliciosa 'Jenny'",
                            Light = "Sol",
                            Name = "Jenny",
                            Price = 379.0,
                            SubCategoryId = 14,
                            ZoneTo = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Medelstarkväxande, populär sort som ger gulgröna äpplen med röd solsida. Har ett fint, fast fruktkött med en sötsyrlig smak. Frisk sort. Kan lagras fram till jul. Pollineras av bl. a 'Alice' och 'Ingrid Marie'. Bäst skörd i soligt läge.",
                            Height = 500,
                            LatinName = "Malus domestica 'Aroma'",
                            Light = "Sol-halvskugga",
                            Name = "Aroma",
                            Price = 520.0,
                            SubCategoryId = 11,
                            ZoneTo = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Svagväxande, populär sort som får stora, medeltidiga skördar med stora, rödgula frukter med ljusviolett daggig yta. Fast fruktkött med söt smak. Självfertil. Ger bäst skörd i soligt läge på väldränerad och näringsrik jord.",
                            Height = 450,
                            LatinName = "Prunus domestica 'Victoria'",
                            Light = "Sol-halvskugga",
                            Name = "Victoria",
                            Price = 799.0,
                            SubCategoryId = 12,
                            ZoneTo = 3
                        },
                        new
                        {
                            Id = 19,
                            Description = "Odlingsvärt litet träd med tät, rundad krona. Vackert ljusgrönt bladverk med vitbrokiga skott som har rosatonad anstrykning på nytillväxten. Trivs i skyddat, soligt läge på väldränerad, näringsrik jord.",
                            Height = 250,
                            LatinName = "Salix integra 'Hakuro-nishiki'",
                            Light = "Sol",
                            Name = "Eukalyptusvide",
                            Price = 799.0,
                            SubCategoryId = 9,
                            ZoneTo = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Färggrann sort med kraftigt, slingrande och täckande växtsätt med frodigt blågrönt bladverk. Blommar rikligt med doftande, brandgula blommor varvat med bronsgula knoppar. Bildar röda, oätliga bär. Trivs i sol till halvskugga på väldränerad, näringsrik jord.3.",
                            Height = 450,
                            LatinName = "Salix caprea 'Kilmarnock'",
                            Light = "Sol",
                            Name = "Hängsälg",
                            Price = 100.0,
                            SubCategoryId = 9,
                            ZoneTo = 6
                        },
                        new
                        {
                            Id = 21,
                            Description = "Med det nätta formatet och det hängande växtsättet passar hängsälgen i kruka väldigt fint men också mitt i en större plantering för att skapa höjd. Fördelen med att den är uppstammad är att man kan plantera olika sommarblommor eller perenner under den. Samma sak när hängsälg står i rabatten, ett litet träd med videkissar blir perfekt med blommor nedanför.",
                            Height = 120,
                            LatinName = "Hydrangea paniculata 'Sundae-Fraise'",
                            Light = "Sol-halvskugga",
                            Name = "Sundae-Fraise",
                            Price = 450.0,
                            SubCategoryId = 15,
                            ZoneTo = 3
                        });
                });

            modelBuilder.Entity("SiasGarden.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "\\images\\products\\product-1\\startbild.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "\\images\\products\\product-2\\startbild.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "\\images\\products\\product-3\\startbild.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "\\images\\products\\product-4\\startbild.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "\\images\\products\\product-5\\startbild.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "\\images\\products\\product-6\\startbild.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "\\images\\products\\product-7\\startbild.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "\\images\\products\\product-8\\startbild.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "\\images\\products\\product-9\\startbild.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "\\images\\products\\product-10\\startbild.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "\\images\\products\\product-11\\startbild.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "\\images\\products\\product-12\\startbild.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "\\images\\products\\product-13\\startbild.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "\\images\\products\\product-14\\startbild.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "\\images\\products\\product-15\\startbild.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "\\images\\products\\product-16\\startbild.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "\\images\\products\\product-17\\startbild.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "\\images\\products\\product-18\\startbild.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "\\images\\products\\product-19\\startbild.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "\\images\\products\\product-20\\startbild.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "\\images\\products\\product-21\\startbild.jpg",
                            ProductId = 21
                        });
                });

            modelBuilder.Entity("SiasGarden.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("SiasGarden.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Kryddväxter"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Löjtnadshjärtan"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Buskrosor"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Rabattrosor"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Klematisar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Kaprifoler"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Prydnadsbuskar"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Bärbuskar"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Prydnadsträd"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "Fruktträd"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "Äpple"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Name = "Plommon"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "Svarta vinbär"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Kivi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Hortensia"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SiasGarden.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SiasGarden.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiasGarden.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SiasGarden.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiasGarden.Models.OrderDetail", b =>
                {
                    b.HasOne("SiasGarden.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiasGarden.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SiasGarden.Models.OrderHeader", b =>
                {
                    b.HasOne("SiasGarden.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.HasOne("SiasGarden.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SiasGarden.Models.ProductImage", b =>
                {
                    b.HasOne("SiasGarden.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SiasGarden.Models.ShoppingCart", b =>
                {
                    b.HasOne("SiasGarden.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiasGarden.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SiasGarden.Models.SubCategory", b =>
                {
                    b.HasOne("SiasGarden.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SiasGarden.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
